server:
  port: 5000

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  datasource:
    initialization-mode: always
    url: "jdbc:postgresql://localhost:5433/postgres"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect